/* Generated by Pyrex 0.9.9 on Sun Oct 11 13:41:12 2015 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "MMTK/arrayobject.h"
#include "MMTK/core.h"
#include "MMTK/universe.h"
#include "MMTK/forcefield.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from bilab.structure.minimization._MMTK_energy_term */


/* Declarations from implementation of bilab.structure.minimization._MMTK_energy_term */

struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm {
  PyFFEnergyTermObject __pyx_base;
  struct __pyx_vtabstruct_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *__pyx_vtab;
  PyObject *universe;
  PyObject *configuration;
};


struct __pyx_vtabstruct_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm {
  void (*c_evaluate)(struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *,PyFFEvaluatorObject *,energy_spec *,energy_data *);
};
static struct __pyx_vtabstruct_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *__pyx_vtabptr_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm;

static PyTypeObject *__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_ndarray = 0;
static PyTypeObject *__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm = 0;
static PyTypeObject *__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyEvaluator = 0;
static PyTypeObject *__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm = 0;

static char __pyx_k1[] = "__init__";
static char __pyx_k2[] = "name";
static char __pyx_k3[] = "term_names";
static char __pyx_k4[] = "range";
static char __pyx_k5[] = "append";
static char __pyx_k6[] = "AttributeError";
static char __pyx_k7[] = "bilab";
static char __pyx_k8[] = "structure";
static char __pyx_k9[] = "minimization";
static char __pyx_k10[] = "Configuration";
static char __pyx_k11[] = "array";
static char __pyx_k12[] = "evaluate";
static char __pyx_k13[] = "energy";
static char __pyx_k14[] = "virial";
static char __pyx_k15[] = "N";
static char __pyx_k16[] = "add";
static char __pyx_k17[] = "gradients";
static char __pyx_k18[] = "force_constants";
static char __pyx_k19[] = "bilab.structure.minimization";
static char __pyx_k20[] = "numpy";

static PyObject *__pyx_n_AttributeError;
static PyObject *__pyx_n_Configuration;
static PyObject *__pyx_n_N;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_add;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_bilab;
static PyObject *__pyx_n_energy;
static PyObject *__pyx_n_evaluate;
static PyObject *__pyx_n_force_constants;
static PyObject *__pyx_n_gradients;
static PyObject *__pyx_n_minimization;
static PyObject *__pyx_n_name;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_range;
static PyObject *__pyx_n_structure;
static PyObject *__pyx_n_term_names;
static PyObject *__pyx_n_virial;

static PyObject *__pyx_k19p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_AttributeError, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_Configuration, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_N, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n___init__, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_add, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_append, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_array, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_bilab, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_energy, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_evaluate, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_force_constants, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_gradients, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_minimization, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_name, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_numpy, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_range, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_structure, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_term_names, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_virial, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k19p, 0, __pyx_k19, sizeof(__pyx_k19)},
  {0, 0, 0, 0}
};



/* Implementation of bilab.structure.minimization._MMTK_energy_term */

static int __pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_universe = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"name","universe",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_name, &__pyx_v_universe)) return -1;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_universe);

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":22 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm), __pyx_n___init__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_INCREF(__pyx_v_name);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_name);
  __pyx_3 = PyTuple_New(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_self);
  Py_INCREF(__pyx_v_universe);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_universe);
  Py_INCREF(__pyx_v_name);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_name);
  PyTuple_SET_ITEM(__pyx_3, 3, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":23 */
  ((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.eval_func = ((void *)__pyx_vtabptr_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm->c_evaluate);

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":24 */
  Py_INCREF(__pyx_v_universe);
  Py_DECREF(((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->universe);
  ((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->universe = __pyx_v_universe;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":25 */
  Py_INCREF(Py_None);
  Py_DECREF(((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->configuration);
  ((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->configuration = Py_None;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bilab.structure.minimization._MMTK_energy_term.PyEnergyTerm.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_universe);
  return __pyx_r;
}

static PyObject *__pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___getattr__(PyObject *__pyx_v_self, PyObject *__pyx_v_name); /*proto*/
static PyObject *__pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___getattr__(PyObject *__pyx_v_self, PyObject *__pyx_v_name) {
  PyObject *__pyx_v_names;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_ssize_t __pyx_5;
  PyObject *__pyx_6 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_name);
  __pyx_v_names = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  if (PyObject_Cmp(__pyx_v_name, __pyx_n_name, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {
    __pyx_2 = PyString_FromString(((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.evaluator_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  if (PyObject_Cmp(__pyx_v_name, __pyx_n_term_names, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":31 */
    __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
    Py_DECREF(__pyx_v_names);
    __pyx_v_names = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":32 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.nterms); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    for (;;) {
      __pyx_4 = PyIter_Next(__pyx_2);
      if (!__pyx_4) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_4;
      __pyx_4 = 0;
      __pyx_3 = PyObject_GetAttr(__pyx_v_names, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
      __pyx_5 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
      __pyx_4 = PyString_FromString((((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.term_names[__pyx_5])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
      __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_4);
      __pyx_4 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":34 */
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    Py_INCREF(__pyx_v_names);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_names);
    __pyx_6 = PyObject_CallObject(((PyObject *)(&PyTuple_Type)), __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_r = __pyx_6;
    __pyx_6 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
    __Pyx_Raise(__pyx_4, __pyx_v_name, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("bilab.structure.minimization._MMTK_energy_term.PyEnergyTerm.__getattr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_names);
  Py_DECREF(__pyx_v_i);
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_name);
  return __pyx_r;
}

static void __pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm_c_evaluate(struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *__pyx_v_self,PyFFEvaluatorObject *__pyx_v_eval,energy_spec *__pyx_v_input,energy_data *__pyx_v_energy) {
  int __pyx_v_do_gradients;
  int __pyx_v_do_fc;
  PyObject *__pyx_v_energy_dict;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  double __pyx_6;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_eval);
  __pyx_v_energy_dict = Py_None; Py_INCREF(Py_None);

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":41 */
  __pyx_v_do_gradients = (__pyx_v_energy->gradients != NULL);

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":42 */
  __pyx_v_do_fc = (__pyx_v_energy->force_constants != NULL);

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":43 */
  __pyx_1 = __pyx_v_self->configuration == Py_None;
  if (__pyx_1) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_bilab); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_structure); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_minimization); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_Configuration); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_INCREF(__pyx_v_self->universe);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self->universe);
    Py_INCREF(((PyObject *)__pyx_v_input->coordinates));
    PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject *)__pyx_v_input->coordinates));
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_self->configuration);
    __pyx_v_self->configuration = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    if (PyObject_SetAttr(__pyx_v_self->configuration, __pyx_n_array, ((PyObject *)__pyx_v_input->coordinates)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  }
  __pyx_L2:;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":48 */
  /*try:*/ {
    __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_self), __pyx_n_evaluate); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L3;}
    __pyx_2 = PyInt_FromLong(__pyx_v_do_gradients); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L3;}
    __pyx_4 = PyInt_FromLong(__pyx_v_do_fc); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L3;}
    __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L3;}
    Py_INCREF(__pyx_v_self->configuration);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_self->configuration);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
    __pyx_2 = 0;
    __pyx_4 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L3;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_v_energy_dict);
    __pyx_v_energy_dict = __pyx_2;
    __pyx_2 = 0;
  }
  goto __pyx_L4;
  __pyx_L3:;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":51 */
  /*except:*/ {
    PyErr_Fetch(&__pyx_4, &__pyx_3, &__pyx_5);

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":52 */
    __pyx_v_energy->error = 1;

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":53 */
    PyErr_Restore(__pyx_4, __pyx_3, __pyx_5);
    __pyx_4 = __pyx_3 = __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_XDECREF(__pyx_4); __pyx_4 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":54 */
  __pyx_2 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_energy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_6 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  (__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.index]) = __pyx_6;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":55 */
  /*try:*/ {
    __pyx_4 = PyFloat_FromDouble((__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.virial_index])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L5;}
    __pyx_3 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_virial); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L5;}
    __pyx_5 = PyNumber_Add(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L5;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_6 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L5;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    (__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.virial_index]) = __pyx_6;
  }
  goto __pyx_L6;
  __pyx_L5:;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":58 */
  __pyx_1 = PyErr_ExceptionMatches(PyExc_KeyError);
  if (__pyx_1) {
    __pyx_v_energy->virial_available = 0;
    goto __pyx_L6;
  }
  goto __pyx_L1;
  __pyx_L6:;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":60 */
  __pyx_1 = __pyx_v_do_gradients;
  if (__pyx_1) {
    /*try:*/ {
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_N); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L8;}
      __pyx_2 = PyObject_GetAttr(__pyx_5, __pyx_n_add); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L8;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_4 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_gradients); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L8;}
      __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_array); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L8;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L8;}
      Py_INCREF(((PyObject *)__pyx_v_energy->gradients));
      PyTuple_SET_ITEM(__pyx_5, 0, ((PyObject *)__pyx_v_energy->gradients));
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
      Py_INCREF(((PyObject *)__pyx_v_energy->gradients));
      PyTuple_SET_ITEM(__pyx_5, 2, ((PyObject *)__pyx_v_energy->gradients));
      __pyx_3 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L8;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    goto __pyx_L9;
    __pyx_L8:;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_5); __pyx_5 = 0;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":65 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_INCREF(PyExc_KeyError);
    PyTuple_SET_ITEM(__pyx_2, 0, PyExc_KeyError);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
    __pyx_3 = 0;
    __pyx_1 = PyErr_ExceptionMatches(__pyx_2);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_1) {
      PyErr_Fetch(&__pyx_5, &__pyx_4, &__pyx_3);

      /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":66 */
      __pyx_v_energy->error = 1;

      /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":67 */
      PyErr_Restore(__pyx_5, __pyx_4, __pyx_3);
      __pyx_5 = __pyx_4 = __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
      Py_XDECREF(__pyx_5); __pyx_5 = 0;
      Py_XDECREF(__pyx_4); __pyx_4 = 0;
      Py_XDECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L9;
    }
    goto __pyx_L1;
    __pyx_L9:;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":68 */
  __pyx_1 = __pyx_v_do_fc;
  if (__pyx_1) {
    /*try:*/ {
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_N); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L11;}
      __pyx_5 = PyObject_GetAttr(__pyx_2, __pyx_n_add); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L11;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_4 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_force_constants); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L11;}
      __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_array); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L11;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L11;}
      Py_INCREF(((PyObject *)__pyx_v_energy->force_constants));
      PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_energy->force_constants));
      PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
      Py_INCREF(((PyObject *)__pyx_v_energy->force_constants));
      PyTuple_SET_ITEM(__pyx_2, 2, ((PyObject *)__pyx_v_energy->force_constants));
      __pyx_3 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L11;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    goto __pyx_L12;
    __pyx_L11:;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_5); __pyx_5 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;

    /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":73 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    Py_INCREF(PyExc_KeyError);
    PyTuple_SET_ITEM(__pyx_5, 0, PyExc_KeyError);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
    __pyx_3 = 0;
    __pyx_1 = PyErr_ExceptionMatches(__pyx_5);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__pyx_1) {
      PyErr_Fetch(&__pyx_2, &__pyx_4, &__pyx_3);

      /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":74 */
      __pyx_v_energy->error = 1;

      /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":75 */
      PyErr_Restore(__pyx_2, __pyx_4, __pyx_3);
      __pyx_2 = __pyx_4 = __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      Py_XDECREF(__pyx_4); __pyx_4 = 0;
      Py_XDECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L12;
    }
    goto __pyx_L1;
    __pyx_L12:;
    goto __pyx_L10;
  }
  __pyx_L10:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("bilab.structure.minimization._MMTK_energy_term.PyEnergyTerm.c_evaluate");
  __pyx_L0:;
  Py_DECREF(__pyx_v_energy_dict);
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_eval);
}
static struct __pyx_vtabstruct_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm __pyx_vtable_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm;

static PyObject *__pyx_tp_new_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *p;
  PyObject *o = __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm->tp_new(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)o);
  *(struct __pyx_vtabstruct_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm **)&p->__pyx_vtab = __pyx_vtabptr_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm;
  p->universe = Py_None; Py_INCREF(Py_None);
  p->configuration = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm(PyObject *o) {
  struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)o;
  Py_XDECREF(p->universe);
  Py_XDECREF(p->configuration);
  __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm->tp_dealloc(o);
}

static int __pyx_tp_traverse_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)o;
  traverseproc t;
  if ((t = __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm->tp_traverse)) {
    e = t(o, v, a); if (e) return e;
  }
  if (p->universe) {
    e = (*v)(p->universe, a); if (e) return e;
  }
  if (p->configuration) {
    e = (*v)(p->configuration, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm(PyObject *o) {
  struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm *)o;
  PyObject *t;
  inquiry c;
  if ((c = __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm->tp_clear)) {
    c(o);
  }
  t = p->universe; 
  p->universe = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->configuration; 
  p->configuration = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static PyObject *__pyx_tp_getattro_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm(PyObject *o, PyObject *n) {
  PyObject *v = PyObject_GenericGetAttr(o, n);
  if (!v && PyErr_ExceptionMatches(PyExc_AttributeError)) {
    PyErr_Clear();
    v = __pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___getattr__(o, n);
  }
  return v;
}

static struct PyMethodDef __pyx_methods_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm[] = {
  {"universe", T_OBJECT, offsetof(struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, universe), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_PyEnergyTerm = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_PyEnergyTerm = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_PyEnergyTerm = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_PyEnergyTerm = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "bilab.structure.minimization._MMTK_energy_term.PyEnergyTerm", /*tp_name*/
  sizeof(struct __pyx_obj_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_PyEnergyTerm, /*tp_as_number*/
  &__pyx_tp_as_sequence_PyEnergyTerm, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_PyEnergyTerm, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  __pyx_tp_getattro_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_PyEnergyTerm, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_traverse*/
  __pyx_tp_clear_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_methods*/
  __pyx_members_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_MMTK_energy_term(void); /*proto*/
PyMODINIT_FUNC init_MMTK_energy_term(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_MMTK_energy_term", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (!__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_ndarray) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 27; goto __pyx_L1;}
  __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm = __Pyx_ImportType("bilab.structure.minimization._MMTK_forcefield", "EnergyTerm", sizeof(PyFFEnergyTermObject)); if (!__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyEvaluator = __Pyx_ImportType("bilab.structure.minimization._MMTK_forcefield", "EnergyEvaluator", sizeof(PyFFEvaluatorObject)); if (!__pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyEvaluator) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_vtabptr_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm = &__pyx_vtable_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm;
  *(void(**)(void))&__pyx_vtable_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm.c_evaluate = (void(*)(void))__pyx_f_5bilab_9structure_12minimization_17_MMTK_energy_term_12PyEnergyTerm_c_evaluate;
  __pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm.tp_base = __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_EnergyTerm;
  __pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm.tp_dict, __pyx_vtabptr_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "PyEnergyTerm", (PyObject *)&__pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  __pyx_ptype_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm = &__pyx_type_5bilab_9structure_12minimization_17_MMTK_energy_term_PyEnergyTerm;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/MMTK/numeric.pxi":37 */
  import_array();

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/MMTK/forcefield.pxi":14 */
  import_MMTK_universe();

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/MMTK/forcefield.pxi":84 */
  import_MMTK_forcefield();

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_k19p, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_bilab, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":14 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_N, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/davecao/apps/bilab/bilab/structure/minimization/_MMTK_energy_term.pyx":38 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bilab.structure.minimization._MMTK_energy_term");
}

static char *__pyx_filenames[] = {
  "_MMTK_energy_term.pyx",
  "numeric.pxi",
  "forcefield.pxi",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    if (value == Py_None)
        value = NULL;
    if (tb == Py_None)
        tb = NULL;
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    if (tb && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
#ifdef __PYX_CHECK_IMPORTED_TYPES
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
#endif
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    return PyImport_Import(py_name);
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
